#!/usr/bin/env python

"""

Usage:

  ./check_bibcodes obscore bibcodes
  
Check the bibcode list - assumed to be in the form

  bibcode  obs_id

against the obscore table.

"""

import sys
import psv

def check_obsids(obsids, fname):

    with open(fname, "r") as fh:
        nlines = 0
        nmiss = 0
        nhack = 0
        for l in fh:
            nlines += 1
            l = l.strip()
            terms = l.split()
            if len(terms) != 2:
                print("ERROR: unable to parse bibcore line '{0}'".format(l))

            else:
                if terms[1] not in obsids:
                    if terms[1] + "_01" not in obsids:
                        print("Missing: {0}".format(l))
                        nmiss += 1

                    else:
                        print("Hacked to _01 for: {0}".format(l))
                        nhack += 1

    if nmiss == 0:
        print("\nCompared {0} bibcodes, none missing.".format(nlines))
        
    else:
        print("\nMissing {0} from {1} bibcodes.".format(nmiss, nlines))

    if nhack > 0:
        print("Hacked {0} items (obsid -> obdis_01)".format(nhack))
                      
def get_obsids(fname):

    (rdr, fh) = psv.get_reader(fname)
    obsids = set()
    for row in rdr:
        obsids.add(psv.get_column(row, "obs_id"))

    fh.close()
    return obsids

if __name__=="__main__":
    nargs = len(sys.argv)
    if len(sys.argv) != 3 :
        print("Usage: {0} <obscore> <bibcode>".format(sys.argv[0]))
        sys.exit(-1)

    obsids = get_obsids(sys.argv[1])
    check_obsids(obsids, sys.argv[2])
