#!/usr/bin/env python

"""
Compare the obs_id columns from obscore.psv and what I assume to be the
obs_id column from obscore_images.psv
"""

import sys
import psv

# Note: we force lower case for comparison; not sure it is
#       correct
#
def get_obsid_tables():

    fname = "obscore.psv"
    (rdr, fh) = psv.get_reader(fname)
    obsids = set()
    for row in rdr:
        obsids.add(psv.get_column(row, "obs_id").lower())

    fh.close()
    return obsids
                
def get_obsid_images():

    fname = "obscore_images.psv"
    fh = open(fname, "r")
    obsids = set()
    for row in fh:
        obsids.add(row.split()[0].lower())

    fh.close()
    return obsids
                
if __name__=="__main__":
    nargs = len(sys.argv)
    if len(sys.argv) != 1 :
        print "Usage: " + sys.argv[0]
        sys.exit(-1)

    ot = get_obsid_tables()
    oi = get_obsid_images()

    print("Table contains {0} obs_id values.".format(len(ot)))
    print("Image contains {0} obs_id values.".format(len(oi)))

    print("Are the two sets of obs_id values disjoint: {0}".format(ot.isdisjoint(oi)))

    
