#!/usr/bin/env python

"""
Usage:

  filter <infile> <colname>=val
  
Filter selected rows from the obscore psv file, creating a new obscore.psv
file on stdout. Very limited functionality at present.

"""

import sys
import psv

def doit(fname, filters):

    (rdr, fh) = psv.get_reader(fname)

    ofh = sys.stdout
    wtr = psv.csv.writer(ofh, dialect='psv')
    
    for row in rdr:
        rvals = psv.row2dict(row)
        flag = True
        for (cname, cval) in filters:
            flag &= (rvals[cname] == cval)

        if flag:
            wtr.writerow(row)
            
    fh.close()

def splitfilter(txt):
    "Convert 'foo=bar' into ('foo', 'bar')"
    n = txt.find("=")
    if n == -1:
        raise ValueError("No = in filter '{0}'!".format(txt))

    elif n == 0:
        raise ValueError("No column name in filter '{0}'!".format(txt))

    else:
        return (txt[:n], txt[n+1:])

if __name__=="__main__":
    nargs = len(sys.argv)
    if len(sys.argv) < 3 :
        print "Usage: " + sys.argv[0] + " <filename> <colname1=val1> [.. <colnameN=valN>]"
        sys.exit(-1)

    fname = sys.argv[1]
    filters = [splitfilter(f) for f in sys.argv[2:]]

    doit(fname, filters)
