#!/usr/bin/env python

"""
Select given columns from the obscore psv file,
where we assume the column names.
"""

import sys
import psv

def select(fname, colnames):

    (rdr, fh) = psv.get_reader(fname)
    for row in rdr:
        out = [psv.get_column(row, cn) for cn in colnames]
        print "  ".join(out)

    fh.close()

if __name__=="__main__":
    nargs = len(sys.argv)
    if len(sys.argv) < 3 :
        print "Usage: " + sys.argv[0] + " <filename> <colname1> [.. <colnameN>]"
        sys.exit(-1)

    fname = sys.argv[1]
    colnames = sys.argv[2:]

    select(fname, colnames)
